apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-claim
  labels:
    app: drupal-test
    tier: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal-test
    tier: drupal
  name: drupal-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal-test
        tier: drupal
    spec:
      initContainers:
        - image: <registry_path>/drupal:<tag>
          name: init-sites-volume
          command: ['/bin/bash', '-c']
          args: ['cp -r /var/www/html/sites /mnt/']
          volumeMounts:
          - mountPath: /mnt
            name: drupal-volume
      containers:
        - image: <registry_path>/drupal:<tag>
          name: drupal-container
          ports:
            - containerPort: 30080
              name: drupal-port
          volumeMounts:
          - mountPath: /var/www/html/modules
            name: drupal-volume
            subPath: modules
          - mountPath: /var/www/html/profiles
            name: drupal-volume
            subPath: profiles
          - mountPath: /var/www/html/sites
            name: drupal-volume
            subPath: sites
          - mountPath: /var/www/html/themes
            name: drupal-volume
            subPath: themes
      volumes:
        - name: drupal-volume
          persistentVolumeClaim:
            claimName: drupal-claim

