apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: drupal-test
    tier: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: sakata-pj
  labels:
    app: drupal-test
    tier: postgres
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: postgres
  template:
    metadata:
      labels:
        app: drupal-test
        tier: postgres
    spec:
      containers:
        - image: postgres:9
          name: postgres-container
          env:
            - name: POSTGRES_DB
              value: <db_name>
            - name: POSTGRES_USER
              value: <db_user_name>
            - name: POSTGRES_PASSWORD
              value: <db_user_password>
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-claim

