apiVersion: v1
kind: ConfigMap
metadata:
  name: sites-conf
  labels:
    app: drupal-test
    tier: nginx
data:
  sites.conf: |
    server {
      listen 8080;
      server_name localhost;

      location / {
        proxy_pass                              http://drupal-service;
        proxy_redirect                          off;
        proxy_set_header Host                   $host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Server     $host;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
      }
    }

